import { GeoPoint, Timestamp, type DocumentData, type FirestoreDataConverter, type QueryDocumentSnapshot, type SnapshotOptions } from 'firebase/firestore'
import type { Device, DeviceComment, DeviceMedia, Inspection, Issue, Repair } from './models'

const timestamp = (value: unknown) => value instanceof Timestamp ? value : null
const text = (value: unknown) => typeof value === 'string' ? value : ''
const number = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : 0
const bool = (value: unknown) => value === true
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []
const converter = <T>(parse: (id: string, data: DocumentData) => T): FirestoreDataConverter<T> => ({ toFirestore: (value) => value as DocumentData, fromFirestore: (snapshot: QueryDocumentSnapshot, options: SnapshotOptions) => parse(snapshot.id, snapshot.data(options)) })

export const deviceConverter = converter<Device>((id, d) => { if (!(d.location instanceof GeoPoint) || !timestamp(d.createdAt) || !timestamp(d.updatedAt)) throw new Error('invalid_device'); return { id, number:number(d.number), name:text(d.name), type:d.type, districtNumber:typeof d.districtNumber === 'number' ? d.districtNumber:null, active:bool(d.active), archived:bool(d.archived), location:d.location, guardianUid:text(d.guardianUid)||null, guardianName:text(d.guardianName)||null, status:d.status, conditionScore:number(d.conditionScore), latestInspectionAt:timestamp(d.latestInspectionAt), latestInspectionId:text(d.latestInspectionId)||null, currentPhotoId:text(d.currentPhotoId)||null, openIssuesCount:number(d.openIssuesCount), createdAt:d.createdAt, createdBy:text(d.createdBy), updatedAt:d.updatedAt, updatedBy:text(d.updatedBy), version:number(d.version) } })
export const inspectionConverter = converter<Inspection>((id,d) => { if (!timestamp(d.inspectionDate)||!timestamp(d.createdAt)) throw new Error('invalid_inspection'); return { id, inspectionDate:d.inspectionDate, inspectorUid:text(d.inspectorUid), inspectorName:text(d.inspectorName), conditionScore:number(d.conditionScore), statusAfterInspection:d.statusAfterInspection, description:text(d.description), recommendations:strings(d.recommendations), approvedForUse:bool(d.approvedForUse), nextInspectionDate:timestamp(d.nextInspectionDate), createdAt:d.createdAt, createdBy:text(d.createdBy), locked:bool(d.locked) } })
export const issueConverter = converter<Issue>((id,d) => { if (!timestamp(d.createdAt)||!timestamp(d.updatedAt)) throw new Error('invalid_issue'); return { id, ...d, title:text(d.title), description:text(d.description), assignedUid:text(d.assignedUid)||null, assignedName:text(d.assignedName)||null, sourceId:text(d.sourceId)||null, dueDate:timestamp(d.dueDate), resolvedAt:timestamp(d.resolvedAt), resolvedByRepairId:text(d.resolvedByRepairId)||null, createdAt:d.createdAt, createdBy:text(d.createdBy), updatedAt:d.updatedAt, updatedBy:text(d.updatedBy) } as Issue })
export const repairConverter = converter<Repair>((id,d) => { if (!timestamp(d.completedAt)||!timestamp(d.createdAt)) throw new Error('invalid_repair'); return { id, ...d, startedAt:timestamp(d.startedAt), completedAt:d.completedAt, description:text(d.description), performedBy:strings(d.performedBy), materials:strings(d.materials), cost:typeof d.cost==='number'?d.cost:null, resolvedIssueIds:strings(d.resolvedIssueIds), conditionBefore:typeof d.conditionBefore==='number'?d.conditionBefore:null, conditionAfter:number(d.conditionAfter), verifiedByUid:text(d.verifiedByUid), verifiedByName:text(d.verifiedByName), createdAt:d.createdAt, createdBy:text(d.createdBy) } as Repair })
export const commentConverter = converter<DeviceComment>((id,d) => { if (!timestamp(d.createdAt)) throw new Error('invalid_comment'); return { id, ...d, content:text(d.content), authorUid:text(d.authorUid), authorName:text(d.authorName), relatedId:text(d.relatedId)||null, createdAt:d.createdAt, convertedToIssueId:text(d.convertedToIssueId)||null, moderatedAt:timestamp(d.moderatedAt), moderatedBy:text(d.moderatedBy)||null } as DeviceComment })
export const mediaConverter = converter<DeviceMedia>((id,d) => { if (!timestamp(d.uploadedAt)) throw new Error('invalid_media'); return { id, ...d, path:text(d.path), relatedId:text(d.relatedId)||null, capturedAt:timestamp(d.capturedAt), uploadedAt:d.uploadedAt, uploadedBy:text(d.uploadedBy), isCurrent:bool(d.isCurrent), replacedBy:text(d.replacedBy)||null, caption:text(d.caption)||null, hidden:bool(d.hidden) } as DeviceMedia })
