import { beforeEach, describe, expect, it, vi } from 'vitest'
import { addDeviceMedia, changeDeviceMedia } from './mediaRepository'
const mocks=vi.hoisted(()=>({get:vi.fn(),set:vi.fn(),update:vi.fn(),getDocs:vi.fn()}))
vi.mock('firebase/firestore',async original=>({...await original<typeof import('firebase/firestore')>(),collection:(_db:unknown,...parts:string[])=>({path:parts.join('/')}),doc:(base:{path?:string},...parts:string[])=>({path:parts.length?parts.join('/'):base.path+'/new',id:parts.at(-1)??'new'}),getDocs:mocks.getDocs,runTransaction:async(_db:unknown,cb:(tx:typeof mocks)=>unknown)=>cb(mocks)}))
const device={version:1,currentPhotoId:'a',primaryPhotoPath:'/images/devices/test/a.webp',photoPaths:['/images/devices/test/a.webp','/images/devices/test/b.webp']}
beforeEach(()=>{vi.clearAllMocks();mocks.getDocs.mockResolvedValue({docs:[]});mocks.get.mockImplementation(async(ref:{path:string})=>({exists:()=>true,data:()=>ref.path==='devices/d'?device:ref.path.endsWith('/a')?{path:device.photoPaths[0],photoStatus:'aktualne',hidden:false}:{path:device.photoPaths[1],photoStatus:'archiwalne',hidden:false}}))})
describe('gallery transactions',()=>{
 it('switches primary without changing photo status or deleting files',async()=>{await changeDeviceMedia('d','b','primary','u');expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({path:'devices/d'}),expect.objectContaining({currentPhotoId:'b',primaryPhotoPath:device.photoPaths[1],version:2}));expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({path:'devices/d/media/b'}),{isCurrent:true});expect(mocks.set).toHaveBeenCalledWith(expect.objectContaining({path:'devices/d/edits/2'}),expect.objectContaining({mediaChange:expect.objectContaining({action:'primary'})}))})
 it('detaches primary, clears cover, retains original media and records history',async()=>{await changeDeviceMedia('d','a','detach','u');expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({path:'devices/d/media/a'}),{hidden:true,isCurrent:false});expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({path:'devices/d'}),expect.objectContaining({photoPaths:[device.photoPaths[1]],currentPhotoId:null,primaryPhotoPath:null}))})
 it('rejects assigning an existing path twice',async()=>{await expect(addDeviceMedia('d',{path:device.photoPaths[0],storageProvider:'public',uploadedBy:'u',capturedAt:null,caption:null,category:'aktualne',relatedType:'device',relatedId:null},null)).rejects.toThrow('już przypisane');expect(mocks.update).not.toHaveBeenCalled()})
})
