vi.mock('./DeviceEditHistory',()=>({DeviceEditHistory:()=>null}))
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { GeoPoint, Timestamp } from 'firebase/firestore'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DevicesRegistryPage, DeviceDetailsPage } from './DeviceViews'
import { ProtectedRoute } from '../auth/ProtectedRoute'
import { DeviceGallery } from './DeviceGallery'
import { DeviceEditForm } from './DeviceEditForm'
import type { Device, DeviceMedia } from './models'
const mocks=vi.hoisted(()=>({role:'member',active:true,details:vi.fn(),update:vi.fn(),change:vi.fn(),add:vi.fn()}))
vi.mock('../auth/useAuth',()=>({useAuth:()=>({role:mocks.role,isActiveMember:mocks.active,loading:false,user:{uid:'u',displayName:'Tester'},profile:{displayName:'Tester'}})}))
vi.mock('./deviceRepository',()=>({updateDevice:mocks.update,createDevice:vi.fn(),archiveDevice:vi.fn()}))
vi.mock('./devicePhotos',()=>({photoUrl:async(path:string)=>path,validPhotoPath:()=>true,uploadDevicePhoto:vi.fn()}))
vi.mock('./mediaRepository',()=>({changeDeviceMedia:mocks.change,addDeviceMedia:mocks.add,replaceCurrentMedia:vi.fn()}))
const stamp=Timestamp.fromMillis(1000)
const device:Device={id:'stable-id',number:'1001',name:'Testowe urządzenie',type:'ambona',districtNumber:null,rewir:'Las',guardianName:'Opiekun Testowy',guardianUid:null,status:'wymaga_naprawy',conditionScore:0,location:new GeoPoint(51,22),active:true,archived:false,createdAt:stamp,createdBy:'u',updatedAt:stamp,updatedBy:'u',version:1,currentPhotoId:'a',primaryPhotoPath:'/images/devices/test/a.webp',photoPaths:['/images/devices/test/a.webp'],latestInspectionAt:null,latestInspectionId:null,openIssuesCount:0,description:'Pełny opis',defects:['Drabina'],recommendations:['Sprawdzić mocowanie'],numberNeedsVerification:true}
vi.mock('./useDeviceData',()=>({useDevices:()=>({devices:[device,{...device,id:'other',type:'pasnik',number:'31',name:'Paśnik',guardianName:null,rewir:null}],loading:false,error:null}),useDeviceDetails:(id:string)=>{mocks.details(id);return {device,loading:false,error:null,inspections:[],issues:[],repairs:[],comments:[],media:[]}}}))
beforeEach(()=>{vi.clearAllMocks();mocks.role='member';mocks.active=true;mocks.update.mockResolvedValue(undefined);vi.spyOn(window,'confirm').mockReturnValue(true)})
const registry=()=>render(<MemoryRouter><DevicesRegistryPage/></MemoryRouter>)
describe('rejestr aplikacji',()=>{
 it('odrzuca przygotowany zapis po aktualizacji dokumentu w tle',()=>{const view=render(<DeviceEditForm device={device} uid="u"/>);fireEvent.submit(screen.getByText('Zapisz metryczkę').closest('form')!);view.rerender(<DeviceEditForm device={{...device,version:2,name:'Zmiana innego administratora'}} uid="u"/>);fireEvent.click(screen.getByText('Potwierdź zapis zmian'));expect(mocks.update).not.toHaveBeenCalled();expect(screen.getByText('Dane zmieniły się. Sprawdź aktualne dane i ponów edycję.')).toBeInTheDocument()})
 it('przełącza karty i tabelę; nazwa i zdjęcie prowadzą do stabilnego ID',async()=>{registry();expect(screen.queryByRole('table')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Tabela'}));expect(screen.getByRole('table')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Nr 1001 — Testowe urządzenie'})).toHaveAttribute('href','/panel/urzadzenia/stable-id');expect(screen.getByRole('link',{name:'Zdjęcie urządzenia 1001'})).toHaveAttribute('href','/panel/urzadzenia/stable-id');await screen.findByAltText('Urządzenie 1001');fireEvent.click(screen.getByRole('button',{name:'Karty'}));expect(screen.queryByRole('table')).not.toBeInTheDocument()})
 it.each(['ambona','pasnik','zwyzka','inne'])('filtruje typ %s',type=>{registry();fireEvent.change(screen.getByLabelText('Typ'),{target:{value:type}});expect(screen.queryByText('Nr 1001 — Testowe urządzenie')!==null).toBe(type==='ambona');expect(screen.queryByText('Nr 31 — Paśnik')!==null).toBe(type==='pasnik')})
 it.each(['1001','opiekun','las'])('wyszukuje numer, opiekuna lub rewir: %s',search=>{registry();fireEvent.change(screen.getByLabelText('Szukaj numeru, opiekuna lub rewiru'),{target:{value:search}});expect(screen.getByText('Nr 1001 — Testowe urządzenie')).toBeInTheDocument();expect(screen.queryByText('Nr 31 — Paśnik')).not.toBeInTheDocument()})
 it('otwiera stronę szczegółową pod właściwą trasą',()=>{render(<MemoryRouter initialEntries={['/panel/urzadzenia/stable-id']}><Routes><Route element={<ProtectedRoute/>}><Route path="/panel/urzadzenia/:id" element={<DeviceDetailsPage/>}/></Route></Routes></MemoryRouter>);expect(mocks.details).toHaveBeenCalledWith('stable-id');expect(screen.getByText('Pełny opis')).toBeInTheDocument();expect(screen.getByText('Drabina')).toBeInTheDocument();expect(screen.getByText('Sprawdzić mocowanie')).toBeInTheDocument();expect(screen.queryByText('Narzędzia administratora')).not.toBeInTheDocument();expect(screen.getByText('Wyślij zgłoszenie')).toBeInTheDocument()})
 it('niezalogowany nie pobiera rejestru szczegółowego',()=>{mocks.active=false;render(<MemoryRouter initialEntries={['/panel/urzadzenia/stable-id']}><Routes><Route element={<ProtectedRoute/>}><Route path="/panel/urzadzenia/:id" element={<DeviceDetailsPage/>}/></Route><Route path="/logowanie" element={<p>Logowanie testowe</p>}/></Routes></MemoryRouter>);expect(screen.getByText('Logowanie testowe')).toBeInTheDocument();expect(mocks.details).not.toHaveBeenCalled()})
 it('admin otrzymuje formularze; member tylko przegląda i komentuje',()=>{mocks.role='admin';render(<MemoryRouter><DeviceDetailsPage/></MemoryRouter>);expect(screen.getByText('Narzędzia administratora')).toBeInTheDocument();expect(screen.getByText('Dodaj zdjęcie')).toBeInTheDocument()})
 it('edycja numeru wymaga podsumowania i zachowuje ID oraz wersję',async()=>{render(<DeviceEditForm device={device} uid="u"/>);fireEvent.change(screen.getByLabelText('Numer'),{target:{value:'4A'}});fireEvent.submit(screen.getByText('Zapisz metryczkę').closest('form')!);expect(mocks.update).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Potwierdź zapis zmian'));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith('stable-id',expect.objectContaining({number:'4A',description:'Pełny opis',conditionScore:0}), 'u',1))})
 it('pokazuje kolizję numeru bez deklarowania sukcesu',async()=>{mocks.update.mockRejectedValue(Error('device_already_exists'));render(<DeviceEditForm device={device} uid="u"/>);fireEvent.submit(screen.getByText('Zapisz metryczkę').closest('form')!);fireEvent.click(screen.getByText('Potwierdź zapis zmian'));expect(await screen.findByText('Ten typ i numer są już zajęte.')).toBeInTheDocument()})
})
const media=[{id:'a',path:'/images/devices/test/a.webp',photoStatus:'aktualne',caption:'Widok A',hidden:false},{id:'b',path:'/images/devices/test/b.webp',photoStatus:'archiwalne',caption:'Widok B',hidden:false}] as DeviceMedia[]
describe('galeria aplikacji',()=>{
 it('pokazuje wszystkie przypisane zdjęcia i oddziela aktualne od archiwalnych',async()=>{render(<DeviceGallery device={device} media={media} admin={false} uid="u"/>);await screen.findByAltText('Widok A');await screen.findByAltText('Widok B');expect(screen.getByText('Widok A · zdjęcie główne')).toBeInTheDocument();expect(screen.queryByText('Ustaw jako główne')).not.toBeInTheDocument()})
 it('administrator ustawia główne i usuwa przypisanie po potwierdzeniu',async()=>{render(<DeviceGallery device={device} media={media} admin uid="u"/>);fireEvent.click(screen.getAllByText('Ustaw jako główne')[1]);await waitFor(()=>expect(mocks.change).toHaveBeenCalledWith('stable-id','b','primary','u'));await waitFor(()=>expect(screen.getAllByText('Usuń przypisanie')[0]).not.toBeDisabled());fireEvent.click(screen.getAllByText('Usuń przypisanie')[0]);await waitFor(()=>expect(mocks.change).toHaveBeenCalledWith('stable-id','a','detach','u'))})
})
