import {readFile} from 'node:fs/promises'
import {initializeTestEnvironment,assertFails,assertSucceeds,type RulesTestEnvironment} from '@firebase/rules-unit-testing'
import {doc,setDoc,getDoc,getDocs,collection,updateDoc,serverTimestamp,GeoPoint,writeBatch} from 'firebase/firestore'
import {beforeAll,beforeEach,afterAll,describe,it,expect,vi} from 'vitest'
const handles=vi.hoisted(()=>({db:null as unknown}))
vi.mock('../../src/lib/firebase',()=>({get db(){return handles.db}}))
import {updateDevice,createDevice} from '../../src/devices/deviceRepository'
import {addDeviceMedia,changeDeviceMedia} from '../../src/devices/mediaRepository'
import {createComment,editComment} from '../../src/devices/commentRepository'
let env:RulesTestEnvironment
const admin={uid:'audit-admin',email:'audit-admin@example.test',displayName:'Admin testowy'},member={uid:'audit-member',email:'audit-member@example.test',displayName:'Member testowy'}
const context=(user=admin)=>env.authenticatedContext(user.uid,{email:user.email}).firestore()
const base=(number:string|number=40,type='ambona')=>({number,type,name:'Test',description:'Opis',guardianName:null,guardianUid:null,rewir:null,districtNumber:null,location:new GeoPoint(51,22),active:true,archived:false,status:'sprawne',conditionScore:4,conditionLabel:null,version:1,createdBy:admin.uid,updatedBy:admin.uid,createdAt:new Date('2026-01-01'),updatedAt:new Date('2026-01-01'),currentPhotoId:null,photoPaths:[],primaryPhotoPath:null})
async function seedRecord(id:string,number:string|number=40,type='ambona'){await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'devices',id),base(number,type)))}
async function trustedIndex(){await env.withSecurityRulesDisabled(async c=>{const db=c.firestore(),snap=await getDocs(collection(db,'devices'));for(const record of snap.docs){const data=record.data(),number=String(data.number).trim().toUpperCase();await setDoc(doc(db,'deviceNumbers',`${data.type}-${number.toLowerCase()}`),{deviceId:record.id,type:data.type,number,updatedBy:admin.uid,updatedAt:serverTimestamp()})}await setDoc(doc(db,'deviceRegistry/identityIndex'),{ready:true})})}
beforeAll(async()=>{if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('LOCAL EMULATOR ONLY');env=await initializeTestEnvironment({projectId:'demo-nemrod40',firestore:{host:'127.0.0.1',port:8080,rules:await readFile('firestore.rules','utf8')}})})
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'authorizedUsers',admin.email),{active:true,role:'admin',displayName:admin.displayName});await setDoc(doc(c.firestore(),'authorizedUsers',member.email),{active:true,role:'member',displayName:member.displayName})});handles.db=context();await seedRecord('random-legacy-A')})
afterAll(async()=>{await env?.clearFirestore();await env?.cleanup()})
describe('AUDIT actual application repositories on demo emulator',()=>{
 it('ordinary description/guardian/GPS on random numeric legacy ID without readiness flag',async()=>{await assertSucceeds(updateDevice('random-legacy-A',{description:'Nowy opis',guardianName:'Test opiekuna',latitude:52,longitude:23},admin.uid,1));const d=(await getDoc(doc(context(),'devices/random-legacy-A'))).data()!;expect(d.number).toBe(40);expect(d.location.latitude).toBe(52);expect(d.googleMaps).toBe('https://maps.google.com/?q=52,23');expect((await getDoc(doc(context(),'devices/random-legacy-A/edits/2'))).exists()).toBe(true)})
 it('full form preserves legacy numeric identity without readiness flag',async()=>{await assertSucceeds(updateDevice('random-legacy-A',{number:'40',type:'ambona',description:'Opis z formularza'},admin.uid,1))})
 it('ordinary guardian edit must not depend on a conflicting legacy number reservation',async()=>{await seedRecord('random-legacy-B',40);await updateDevice('random-legacy-A',{description:'Pierwsza edycja'},admin.uid,1);await assertSucceeds(updateDevice('random-legacy-B',{guardianName:'Drugi opiekun'},admin.uid,1))})
 it('unchanged logical number 4a must not block description edit before index activation',async()=>{await seedRecord('random-legacy-A','4a');await assertSucceeds(updateDevice('random-legacy-A',{number:'4A',type:'ambona',description:'Tylko opis'},admin.uid,1))})
 it('adding/primary/status/detachment of photos without readiness flag',async()=>{const id=await addDeviceMedia('random-legacy-A',{path:'/images/devices/test/a.webp',storageProvider:'public',category:'aktualne',relatedType:'device',relatedId:null,caption:null,capturedAt:null,uploadedBy:admin.uid},null);await changeDeviceMedia('random-legacy-A',id,'primary',admin.uid);await changeDeviceMedia('random-legacy-A',id,'archiwalne',admin.uid);await changeDeviceMedia('random-legacy-A',id,'detach',admin.uid);expect((await getDoc(doc(context(),'devices/random-legacy-A/media',id))).data()?.hidden).toBe(true);expect((await getDocs(collection(context(),'deviceNumbers'))).empty).toBe(true)})
 it('member can comment but cannot edit device, photos or comments',async()=>{handles.db=context(member);const comment=await assertSucceeds(createComment('random-legacy-A',{type:'uwaga',content:'Uwaga',relatedType:'device',relatedId:null},{uid:member.uid,name:member.displayName}));await assertFails(updateDevice('random-legacy-A',{description:'Niedozwolone'},member.uid,1));await assertFails(addDeviceMedia('random-legacy-A',{path:'/images/devices/test/a.webp',storageProvider:'public',category:'aktualne',relatedType:'device',relatedId:null,caption:null,capturedAt:null,uploadedBy:member.uid},null));await assertFails(editComment('random-legacy-A',comment.id,'Zmiana',member.uid))})
 it('complete index includes random IDs and rejects same-type collision',async()=>{await seedRecord('random-legacy-B','41');await trustedIndex();expect((await getDoc(doc(context(),'deviceNumbers/ambona-40'))).data()?.deviceId).toBe('random-legacy-A');await expect(updateDevice('random-legacy-A',{number:'41'},admin.uid,1)).rejects.toThrow('device_already_exists')})
 it('different types may have identical numbers',async()=>{await seedRecord('random-legacy-B','41','pasnik');await trustedIndex();await assertSucceeds(updateDevice('random-legacy-B',{number:'40'},admin.uid,1));expect((await getDoc(doc(context(),'deviceNumbers/pasnik-40'))).data()?.deviceId).toBe('random-legacy-B')})
 it('concurrent same-type reservation allows only one writer',async()=>{await seedRecord('random-legacy-B','41');await trustedIndex();const outcomes=await Promise.allSettled([updateDevice('random-legacy-A',{number:'1001'},admin.uid,1),updateDevice('random-legacy-B',{number:'1001'},admin.uid,1)]);expect(outcomes.filter(x=>x.status==='fulfilled')).toHaveLength(1)})
 it('renumber preserves document ID, creation audit and child comment',async()=>{const comment=await createComment('random-legacy-A',{type:'uwaga',content:'Historia',relatedType:'device',relatedId:null},{uid:admin.uid,name:admin.displayName});await trustedIndex();await updateDevice('random-legacy-A',{number:'1001'},admin.uid,1);const result=(await getDoc(doc(context(),'devices/random-legacy-A'))).data()!;expect(result.number).toBe('1001');expect(result.createdAt.toDate().toISOString()).toBe('2026-01-01T00:00:00.000Z');expect((await getDoc(comment)).exists()).toBe(true);expect((await getDoc(doc(context(),'devices/ambona-1001'))).exists()).toBe(false)})
 it('missing readiness blocks creation and renumber; member/admin cannot set readiness',async()=>{await assertFails(updateDevice('random-legacy-A',{number:'1001'},admin.uid,1));await assertFails(createDevice({number:'42',type:'ambona',name:'Nowe',districtNumber:null,latitude:51,longitude:22,guardianUid:null,guardianName:null,status:'sprawne',conditionScore:4,active:true},admin.uid));await assertFails(setDoc(doc(context(),'deviceRegistry/identityIndex'),{ready:true}));await assertFails(setDoc(doc(context(member),'deviceRegistry/identityIndex'),{ready:true}))})
 it('reused old comment history must not authorize unrecorded content changes',async()=>{const comment=await createComment('random-legacy-A',{type:'uwaga',content:'A',relatedType:'device',relatedId:null},{uid:admin.uid,name:admin.displayName});await editComment('random-legacy-A',comment.id,'B',admin.uid);const oldEdit=(await getDoc(comment)).data()!.lastEditId;await editComment('random-legacy-A',comment.id,'A',admin.uid);await assertFails(updateDoc(comment,{content:'C bez historii',lastEditId:oldEdit,moderatedBy:admin.uid,moderatedAt:serverTimestamp()}))})
 it('OBSERVATION readiness true without complete index permits a duplicate through direct admin writes',async()=>{await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'deviceRegistry/identityIndex'),{ready:true}));const db=context(),batch=writeBatch(db);batch.set(doc(db,'devices/ambona-40'),{...base('40'),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(db,'deviceNumbers/ambona-40'),{deviceId:'ambona-40',number:'40',type:'ambona',updatedBy:admin.uid,updatedAt:serverTimestamp()});await assertSucceeds(batch.commit());expect((await getDocs(collection(db,'devices'))).size).toBe(2)})
})
